// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseEmpty: typeof import('./src/components/baseEmpty/index.vue')['default']
    Browse: typeof import('./src/components/themeDialog/browse.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Mask: typeof import('./src/components/mask/index.vue')['default']
    NavPhDrawer: typeof import('./src/components/navPhDrawer/index.vue')['default']
    OpenIcon: typeof import('./src/components/navPhDrawer/openIcon.vue')['default']
    Reaction: typeof import('./src/components/themeDialog/reaction.vue')['default']
  }
}

export { }
